version: '3.8'
services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword123!" # Replace with your password
      ACCEPT_EULA: "Y"
      MSSQL_DISABLE_ENCRYPTION: "true" # Add this line
    volumes:
      - identitydb_data:/var/opt/mssql
  maindb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword123!" # Replace with your password
      ACCEPT_EULA: "Y"
      MSSQL_DISABLE_ENCRYPTION: "true" # Add this line
    volumes:
      - maindb_data:/var/opt/mssql
volumes:
  identitydb_data:
  maindb_data: